### ISSUE TITLE
Add reference to original source of the crxToZip logic + fix calcLength function

### ISSUE THREAD

**Issue by Rob--W** [peerigon/unzip-crx#7]
The [`crxToZip` function in your library][1] is copied from crx2ff. While crx2ff [credits the original source of the logic][2] (https://github.com/Rob--W/crxviewer/blob/master/src/lib/crx-to-zip.js), your library does not. I suggest that you add a link to the original source of the logic for future reference and to avoid propagation of errors.

Since the original logical fork by crx2ff, I updated the CRX parser to support the CRX3 format and to fix a flaw in the `calcLength` function. Someone has already sent a PR for the CRX3 format (#5), so you could merge that and add another patch to fix the `calcLength` flaw: https://github.com/Rob--W/crxviewer/commit/420214409ed62aa88de877efbd45f0cf5cd9cb3a

[1]: https://github.com/peerigon/unzip-crx/blob/b0ea601d83a0666162e156d474778e64bbaba119/src/index.js#L13-L47
[2]: https://github.com/abarreir/crx2ff/blob/826a20574c210f48a4f55aedffc38b56a8339a0a/libs/utils/unzip-crx.js#L70

**Comment by hpohlmeyer** [comment]
Thanks for pointing that out! We merged #5 today and added credit to the original source in #8.  
Let me know, if this is fine with you.

And apologies for not giving credit in the first place.
